In [2]:
import pandas as pd
credits=pd.read_csv(r'data\tmdb_5000_credits.csv')
movies=pd.read_csv(r'data\tmdb_5000_movies.csv')

In [3]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
#merging both datasets
movies=movies.merge(credits,on='title')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies.drop(['budget','homepage','original_language','original_title','popularity','production_companies','production_countries','release_date','revenue','runtime',
             'spoken_languages','status','tagline','vote_average','vote_count','id'],inplace=True,axis=1)

In [8]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,Spectre,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

genres      0
keywords    0
overview    3
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.isnull().sum()

genres      0
keywords    0
overview    0
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [12]:
movies.duplicated().sum()

np.int64(0)

In [13]:
movies.head(2)

,genres,keywords,overview,title,movie_id,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [14]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
# we have to convert genres in this format ['Action','Adventure','SciFi']

In [16]:
import ast
def genre_convert(obj):
    m=ast.literal_eval(obj)
    list=[]
    for i in m:
        list.append(i['name'])
    return list

In [17]:
movies['genres']=movies['genres'].apply(genre_convert)

In [18]:
movies.head(2)

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [19]:
movies['keywords']=movies['keywords'].apply(genre_convert)
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [20]:
movies.head(1)

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [21]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [22]:
def cast_convert(obj):
    m=ast.literal_eval(obj)
    list=[]
    count=0
    for i in m:
        if count!=5:
            list.append(i['name'])
            count=count+1
            
        else:
            break
    return list

In [23]:
movies['cast']=movies['cast'].apply(cast_convert)

In [24]:
movies.head(1)

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [25]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [26]:
import numpy as np
def fetch_director(obj):
    
    m=ast.literal_eval(obj)
    list=[]
    for i in m:
        if i['job']=='Director':
            list.append(i['name'])
    return list

In [27]:
movies['crew']=movies['crew'].apply(fetch_director)

In [28]:
movies.head(2)

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]

In [29]:
movies.isnull().sum()

genres      0
keywords    0
overview    0
title       0
movie_id    0
cast        0
crew        0
dtype: int64

In [30]:

def space_remove(obj):
    for i in range(len(obj)):
        obj[i] = obj[i].replace(' ', '')
    return obj

In [31]:
movies['keywords']=movies['keywords'].apply(space_remove)
movies['cast']=movies['cast'].apply(space_remove)
movies['crew']=movies['crew'].apply(space_remove)
movies['genres']=movies['genres'].apply(space_remove)

In [32]:
movies.head()

,genres,keywords,overview,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,206647,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,49026,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [33]:
movies['tags']=movies['genres']+movies['keywords']+movies['cast']+movies['crew']+movies['overview']

In [34]:
movies.drop(['genres','keywords','cast','crew','overview'],axis=1,inplace=True)

In [35]:
movies.head()

,title,movie_id,tags
0,Avatar,19995,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,Spectre,206647,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,John Carter,49529,"[Action, Adventure, ScienceFiction, basedonnov..."

In [36]:
movies['tags']=movies['tags'].apply(lambda x:" ".join(i for i in x))

In [37]:
movies.head()

,title,movie_id,tags
0,Avatar,19995,Action Adventure Fantasy ScienceFiction cultur...
1,Pirates of the Caribbean: At World's End,285,Adventure Fantasy Action ocean drugabuse exoti...
2,Spectre,206647,Action Adventure Crime spy basedonnovel secret...
3,The Dark Knight Rises,49026,Action Crime Drama Thriller dccomics crimefigh...
4,John Carter,49529,Action Adventure ScienceFiction basedonnovel m...

In [38]:
movies['tags'][0]

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez JamesCameron In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [39]:
#text preprocessing

In [40]:
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from textblob import TextBlob

def text_preprocessing(txt):
    #text to lower case
    txt=txt.lower()
    
    #removing punctuation
    translator=str.maketrans("","",string.punctuation)
    txt=txt.translate(translator)
    
    #remove digits
    txt="".join([word for word in txt if not word.isdigit()])
    
    #text without whitespace
    # txt=" ".join(txt.split())
    
    #txt normalization
    # txt=str(TextBlob(txt).correct())
    
    
    #word tokenize
    txt=word_tokenize(txt) #list

    #stop words removal
    stop_words=set(stopwords.words('english'))
    filtered_txt=[word for word in txt if word not in stop_words]
    
    #stemming
    stemmer=PorterStemmer()
    txt=[stemmer.stem(word) for word in filtered_txt]
    
    #lemmatization
    lemmatizer=WordNetLemmatizer()
    txt=[lemmatizer.lemmatize(word) for word in txt]
    
    return txt

In [41]:
import swifter
movies['tags']=movies['tags'].swifter.apply(text_preprocessing)
movies.head()

Pandas Apply:   0%|          | 0/4806 [00:00<?, ?it/s]

,title,movie_id,tags
0,Avatar,19995,"[action, adventur, fantasi, sciencefict, cultu..."
1,Pirates of the Caribbean: At World's End,285,"[adventur, fantasi, action, ocean, drugabus, e..."
2,Spectre,206647,"[action, adventur, crime, spi, basedonnovel, s..."
3,The Dark Knight Rises,49026,"[action, crime, drama, thriller, dccomic, crim..."
4,John Carter,49529,"[action, adventur, sciencefict, basedonnovel, ..."

In [42]:
movies['tags']=movies['tags'].apply(lambda x: " ".join(word for word in x))
movies.head()

,title,movie_id,tags
0,Avatar,19995,action adventur fantasi sciencefict culturecla...
1,Pirates of the Caribbean: At World's End,285,adventur fantasi action ocean drugabus exotici...
2,Spectre,206647,action adventur crime spi basedonnovel secreta...
3,The Dark Knight Rises,49026,action crime drama thriller dccomic crimefight...
4,John Carter,49529,action adventur sciencefict basedonnovel mar m...

In [43]:
#vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer=TfidfVectorizer(max_features=5000)
vectors=vectorizer.fit_transform(movies['tags'])
vectorizer.get_feature_names_out()

array(['aaron', 'aaroneckhart', 'aarontaylorjohnson', ..., 'zone', 'zoo',
       'zooeydeschanel'], dtype=object)

In [44]:
vectors.shape

(4806, 5000)

In [47]:
import pickle
pickle.dump(vectors,open('vectors.pkl','wb'))

In [ ]:
movies.head()

,title,movie_id,tags
0,Avatar,19995,action adventur fantasi sciencefict culturecla...
1,Pirates of the Caribbean: At World's End,285,adventur fantasi action ocean drugabus exotici...
2,Spectre,206647,action adventur crime spi basedonnovel secreta...
3,The Dark Knight Rises,49026,action crime drama thriller dccomic crimefight...
4,John Carter,49529,action adventur sciencefict basedonnovel mar m...

In [ ]:
import pickle
movies_with_id={'title':movies['title'],
        'movie_id':movies['movie_id']}
pickle.dump(movies_with_id,open('movies_with_id.pkl','wb'))

In [ ]:
#cosine distance
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [ ]:
l=sorted(list(enumerate([float(dist) for dist in list(similarity[0])])),reverse=True,key=lambda x:x[1])
l

[(0, 1.0000000000000004),
 (2405, 0.23204131884951745),
 (3606, 0.16763876890886345),
 (778, 0.160536491522253),
 (260, 0.15167623532509428),
 (1916, 0.15013641756281312),
 (47, 0.14682580334805137),
 (539, 0.14590787706422062),
 (942, 0.14346498639400088),
 (2936, 0.13899108997994053),
 (507, 0.1385519925713491),
 (582, 0.13821755286698298),
 (1214, 0.13742670017574435),
 (3536, 0.13653378332008717),
 (3728, 0.13587151261585714),
 (438, 0.13392506688101524),
 (2782, 0.13292582898789063),
 (1342, 0.1323954265193172),
 (83, 0.12950900553154793),
 (1087, 0.12905098734498444),
 (311, 0.12851735615914336),
 (2280, 0.12776549082221583),
 (2200, 0.1249532689667109),
 (300, 0.12450232913507411),
 (4336, 0.1242634039469616),
 (74, 0.12421995216606499),
 (4046, 0.12320277344019409),
 (513, 0.12243152641998312),
 (1346, 0.12225108354099049),
 (2969, 0.11802496794464526),
 (4190, 0.1177459630201117),
 (1827, 0.11695655462540969),
 (838, 0.11666108129047335),
 (595, 0.11640794750968149),
 (1941, 0.11635734133371417),
 (3671, 0.11552283422376028),
 (1095, 0.11454274840611711),
 (1202, 0.11439507827004494),
 (91, 0.11422655477420346),
 (301, 0.11337568837801554),
 (3160, 0.11263927139152026),
 (322, 0.11215544899526256),
 (1327, 0.11104282662517513),
 (1069, 0.11094833264568868),
 (3325, 0.11090114283152025),
 (4228, 0.10996999408328197),
 (373, 0.10982275952172103),
 (305, 0.1097277079636664),
 (184, 0.10919873728002105),
 (1054, 0.10899580553601117),
 (3441, 0.10871133667555521),
 (1440, 0.10858209065324481),
 (466, 0.1079454986723334),
 (1319, 0.1079408809289321),
 (3952, 0.10673557598768849),
 (2511, 0.10585015730052384),
 (2869, 0.10554185758258916),
 (1199, 0.10528151227224392),
 (2580, 0.10527891414691053),
 (577, 0.10390267946305293),
 (56, 0.10311914243689244),
 (529, 0.10295988561129618),
 (4405, 0.10287835187858979),
 (94, 0.10230818507853522),
 (236, 0.10181889898598327),
 (2727, 0.0994228374869269),
 (220, 0.09937160984257055),
 (149, 0.0991070274216965),
 (775, 0.0977839678682666),
 (973, 0.09753853351814988),
 (878, 0.09723328264973519),
 (1273, 0.09664093410154338),
 (27, 0.09554330032101589),
 (2968, 0.09475697830844501),
 (3374, 0.09424933688319202),
 (1475, 0.09368534561883395),
 (2697, 0.09203450547099956),
 (3980, 0.09184482346174877),
 (1353, 0.09127222484039518),
 (2997, 0.09067282298940663),
 (1192, 0.09054787931641455),
 (1711, 0.09049839688077618),
 (1533, 0.09027836704491847),
 (2329, 0.09023086819606065),
 (172, 0.09020588262281956),
 (843, 0.0899953316376559),
 (1978, 0.0899872687493261),
 (36, 0.08946065503448748),
 (3974, 0.0892636314513873),
 (740, 0.08901614627882626),
 (151, 0.088865599668949),
 (972, 0.08680884882304099),
 (3626, 0.08678776802025527),
 (502, 0.08667480288909989),
 (579, 0.08647927230860777),
 (1770, 0.08640720902704387),
 (4, 0.08574433457762787),
 (95, 0.08564540616165336),
 (342, 0.08560360317020005),
 (18, 0.08544384964403476),
 (3997, 0.08480178277863794),
 (3407, 0.08464962038386115),
 (1320, 0.0845466531471867),
 (1556, 0.0840358309546709),
 (4353, 0.08399701739421386),
 (3781, 0.08359635297968863),
 (1961, 0.08337457246579763),
 (279, 0.08284081598478431),
 (476, 0.08234404420160837),
 (3091, 0.08195981205804483),
 (2132, 0.08158322929943931),
 (1493, 0.08120815593996115),
 (41, 0.0811834586671014),
 (168, 0.08093340450257797),
 (4640, 0.08022021620202442),
 (67, 0.0799573109093949),
 (461, 0.07990178629167793),
 (1147, 0.07981677621078521),
 (1218, 0.07975122352470507),
 (61, 0.0788094231935301),
 (1743, 0.07878271425726474),
 (2785, 0.07863453549566689),
 (1029, 0.07789678678288824),
 (1200, 0.0778601651753976),
 (1176, 0.07770364412549288),
 (206, 0.07752089040599787),
 (1397, 0.07737824322594589),
 (3193, 0.07704338273104155),
 (777, 0.0762094866882569),
 (3145, 0.07588075569360332),
 (1379, 0.07564212453464557),
 (557, 0.07533811573431366),
 (3233, 0.0749562108184351),
 (1374, 0.07444092699143626),
 (661, 0.07439097745281559),
 (3307, 0.0737909886111486),
 (549, 0.07366037702503675),
 (43, 0.07365832858488869),
 (294, 0.07353232191811783),
 (1299, 0.0732705216054606),
 (1804, 0.07324637383757593),
 (275, 0.07311946332903084),
 (3460, 0.07297666646485541),
 (2249, 0.072090516571003),
 (1612, 0.07206606106947705),
 (2630, 0.07193968667472421),
 (4077, 0.07164502064821895),
 (3299, 0.07164270492235535),
 (158, 0.07159399116912432),
 (1275, 0.07137209730283253),
 (1164, 0.0713343650080305),
 (4040, 0.07083379239223539),
 (52, 0.07078891624588922),
 (432, 0.0705027001645408),
 (1451, 0.07047392385074047),
 (2543, 0.07039040567960188),
 (634, 0.06987917554166084),
 (1271, 0.0694236828249058),
 (1355, 0.06941194106931622),
 (931, 0.06937600537985451),
 (2756, 0.0692786940578885),
 (108, 0.06915720702881951),
 (4538, 0.06902480002675661),
 (1934, 0.06840959078073688),
 (46, 0.06839085293041039),
 (2616, 0.06824800116697677),
 (495, 0.06800558973788094),
 (150, 0.06794473030733342),
 (2640, 0.06788558499983993),
 (2788, 0.06775547516006358),
 (1508, 0.06766298356095785),
 (1000, 0.06763311235553271),
 (1013, 0.06758965212323051),
 (1761, 0.06742514779660198),
 (889, 0.06718368431759515),
 (3779, 0.06706694145972741),
 (422, 0.06705670953174275),
 (3620, 0.06701470815674523),
 (2231, 0.06678919161865261),
 (1842, 0.0663105521203997),
 (1469, 0.06626487549369299),
 (900, 0.0661412123342907),
 (1635, 0.0658256695497104),
 (454, 0.06570501797127633),
 (239, 0.06516948093568321),
 (2246, 0.06515670291341878),
 (1570, 0.0646344436349691),
 (855, 0.06452380750312152),
 (847, 0.06451757047318636),
 (1819, 0.06444670145473982),
 (568, 0.06439226918510058),
 (3081, 0.06412205643399496),
 (1737, 0.06399857281531282),
 (1484, 0.06386571433924426),
 (4468, 0.06352965301218873),
 (4016, 0.06347976024739764),
 (4568, 0.0631602808620565),
 (332, 0.06307209528649613),
 (2129, 0.06287100973855052),
 (1741, 0.06285733234023048),
 (44, 0.0625349942281774),
 (647, 0.06251276441709527),
 (111, 0.06233301301992869),
 (312, 0.062265822624778325),
 (635, 0.062235559918749433),
 (1798, 0.06217474385696901),
 (1414, 0.06189065524793521),
 (4257, 0.0616622571182156),
 (127, 0.06131317250132383),
 (692, 0.0611658450123079),
 (668, 0.06116219016500172),
 (2552, 0.06111004294498739),
 (3100, 0.061054112095577116),
 (2670, 0.06099620802340737),
 (2804, 0.060951586696622866),
 (2368, 0.060936770804612184),
 (587, 0.06052750196424497),
 (2709, 0.06041300438857121),
 (2648, 0.06035792927989585),
 (483, 0.06024598177807189),
 (1369, 0.05985076846831143),
 (3114, 0.05983466695239412),
 (643, 0.05973992112679467),
 (2736, 0.05971123456885752),
 (230, 0.059573678926063675),
 (7, 0.05921496758128672),
 (2492, 0.059112883675494166),
 (2446, 0.05905553264061415),
 (281, 0.05896858818238892),
 (1392, 0.05880777594195373),
 (4545, 0.058747613232194636),
 (1154, 0.05861009518837054),
 (1875, 0.05845785365884234),
 (1786, 0.05843005175799213),
 (3107, 0.05828893584494254),
 (541, 0.05828301197278599),
 (1527, 0.058236827213878156),
 (31, 0.058177990859014546),
 (2836, 0.05816511223979134),
 (1874, 0.0581341922319959),
 (908, 0.05793848610948519),
 (1696, 0.05791680016754244),
 (1576, 0.05779582533104095),
 (4043, 0.057771807876997316),
 (4196, 0.057710262616151385),
 (449, 0.05755591982282071),
 (282, 0.057366189727316594),
 (589, 0.057197522822788824),
 (1084, 0.056972421668627676),
 (2105, 0.05688080037953212),
 (1442, 0.056724287434169476),
 (3718, 0.05667933931839714),
 (2484, 0.0566378102002943),
 (581, 0.05653031723792527),
 (2177, 0.05625197758483688),
 (1080, 0.05616103701434301),
 (2502, 0.056150999971694655),
 (4587, 0.05611884517860097),
 (297, 0.05586284862410783),
 (68, 0.05586044547906177),
 (249, 0.05583984119359886),
 (2783, 0.05560008910802535),
 (3046, 0.05554034088409669),
 (1295, 0.05552999965619908),
 (3659, 0.05507406710249621),
 (45, 0.05505650702647655),
 (1143, 0.054828451077197096),
 (487, 0.05447535506853365),
 (2108, 0.054399232503418986),
 (3872, 0.054377383513318875),
 (3462, 0.054190533471466795),
 (87, 0.05407645929671341),
 (3006, 0.05405423416471862),
 (1005, 0.05395415885529105),
 (456, 0.053934566248682266),
 (1664, 0.0539226773321459),
 (1894, 0.05384284897481948),
 (3551, 0.053709966751744026),
 (1435, 0.05369300975841696),
 (2237, 0.053655879582830926),
 (646, 0.053645114994561156),
 (75, 0.053561083757143524),
 (4506, 0.053417854284739164),
 (4793, 0.053217076206799656),
 (505, 0.053105675697869094),
 (134, 0.05310071929516226),
 (3210, 0.053038079411665245),
 (3226, 0.05281590952050394),
 (139, 0.052797595311565054),
 (3439, 0.052647207280425476),
 (2243, 0.05262959819251992),
 (1272, 0.05248597885468198),
 (3115, 0.05206055102095544),
 (3446, 0.052040592913783434),
 (3595, 0.05194072475009536),
 (3628, 0.05192007971733471),
 (5, 0.05189577782188195),
 (1128, 0.05159550032630442),
 (1276, 0.051555001974676225),
 (564, 0.05143640091987922),
 (4578, 0.051412472689342834),
 (1613, 0.05139002193971015),
 (2056, 0.05137049957706917),
 (3928, 0.05134677595296255),
 (2165, 0.05130839379900594),
 (1663, 0.051283834765658814),
 (2374, 0.05127885416584353),
 (4118, 0.05122932296444655),
 (535, 0.05116349340156097),
 (4559, 0.05097197354820552),
 (4412, 0.050851861391633967),
 (2656, 0.05082143213049713),
 (2215, 0.0507703483817557),
 (4305, 0.05060005915770076),
 (812, 0.05056844009993646),
 (170, 0.0505624756112647),
 (754, 0.05045826613727221),
 (2149, 0.05039792941457458),
 (1401, 0.050328796238684685),
 (2768, 0.05032169340140658),
 (4179, 0.05031970443081839),
 (671, 0.05022791444308094),
 (3734, 0.050158397610017356),
 (3352, 0.05015419821982887),
 (307, 0.05006788741181819),
 (228, 0.05005965207423481),
 (404, 0.05002474140609999),
 (2525, 0.04993954699732098),
 (859, 0.04975997876003228),
 (4408, 0.04937079577055686),
 (48, 0.04933958648389706),
 (17, 0.049319709471311306),
 (4325, 0.049267022257791594),
 (3429, 0.04917656804698074),
 (2644, 0.0490641657452895),
 (898, 0.04893062416617037),
 (1610, 0.04892649968569449),
 (2790, 0.04891630270703154),
 (2714, 0.04891195833989116),
 (2155, 0.04872407013046411),
 (1302, 0.04867590526058285),
 (808, 0.048579754281821735),
 (166, 0.04856905121125639),
 (99, 0.0484850510657492),
 (473, 0.04840948797780696),
 (3476, 0.048353954831571545),
 (2195, 0.048301651617726024),
 (939, 0.048237995357147276),
 (752, 0.04818161801195016),
 (223, 0.04790483537794126),
 (262, 0.04764041766525813),
 (4718, 0.04754933107888598),
 (3216, 0.04750909524047169),
 (626, 0.04743577094887778),
 (26, 0.04728961781768281),
 (510, 0.04727792615834687),
 (2534, 0.04726023143126133),
 (4266, 0.04722983411751806),
 (141, 0.047032636203784645),
 (1043, 0.04703115555213661),
 (2144, 0.04699249407182718),
 (3338, 0.046976057760162414),
 (570, 0.04695602827849374),
 (1246, 0.046722187994877346),
 (1925, 0.04672045446398365),
 (480, 0.04652430245308908),
 (1107, 0.046452334586567945),
 (286, 0.04644093937875261),
 (486, 0.04643961622958256),
 (3933, 0.04639876621828849),
 (4451, 0.046351254178046565),
 (1014, 0.04622463549530095),
 (2571, 0.04622097491436539),
 (4673, 0.04618878596047119),
 (854, 0.046143140462834),
 (3699, 0.046141284333420296),
 (2435, 0.04612034098356322),
 (174, 0.04595488801826812),
 (2239, 0.04571314960286555),
 (3026, 0.04563922135680373),
 (4626, 0.04563535544535525),
 (1035, 0.04554735970240399),
 (4654, 0.04547968366446446),
 (1450, 0.04538251210004918),
 (2864, 0.04528673433340007),
 (2089, 0.045223329613096525),
 (2759, 0.04518069853411319),
 (3540, 0.04506252495597229),
 (787, 0.04505276690906955),
 (3879, 0.04499906673067682),
 (222, 0.04498550790474787),
 (1482, 0.04497571183351574),
 (4624, 0.04492487317805306),
 (2813, 0.044825169214272355),
 (72, 0.044801513033350795),
 (270, 0.04478288363547203),
 (3753, 0.044675877044562246),
 (363, 0.044613529362308925),
 (674, 0.04456352029696462),
 (562, 0.044394835403833294),
 (870, 0.04439010076850138),
 (1552, 0.04432071520435358),
 (246, 0.04430400163610117),
 (1463, 0.044026802852234884),
 (4803, 0.04395822522152091),
 (256, 0.04393045661280025),
 (123, 0.04393044702770662),
 (3447, 0.0438774635008119),
 (2014, 0.043779052822153094),
 (187, 0.04376738456977715),
 (415, 0.04371861037017675),
 (1530, 0.04370618222037369),
 (1156, 0.04358805919265263),
 (1828, 0.04357018273743405),
 (1682, 0.04338605695313022),
 (678, 0.04330438646252214),
 (2809, 0.043270056474379634),
 (3180, 0.04320838810369401),
 (2779, 0.04316555418678975),
 (283, 0.04315206689040854),
 (1604, 0.04303831433542596),
 (1856, 0.042961206799707),
 (278, 0.04288610763828005),
 (1094, 0.04284958917791891),
 (1179, 0.042842701552153674),
 (4241, 0.04282574534660354),
 (2385, 0.04274489817485514),
 (448, 0.04272187046187374),
 (1608, 0.042656470697762475),
 (375, 0.0425512489163311),
 (4017, 0.042484010173505046),
 (1404, 0.042463320926783454),
 (632, 0.042439066686458735),
 (2071, 0.04243150724631574),
 (995, 0.042389214194629085),
 (4652, 0.04235292028761719),
 (2890, 0.042155442537189454),
 (1436, 0.042138539945541766),
 (1765, 0.04209484364470792),
 (85, 0.041993485861756136),
 (1292, 0.041993396698413385),
 (420, 0.04192722711458411),
 (1159, 0.0419270983246636),
 (70, 0.041899004510955774),
 (3421, 0.04189765169720926),
 (574, 0.04188436106354587),
 (4532, 0.04184177852870162),
 (193, 0.04183840150603828),
 (3204, 0.04180972618067228),
 (4343, 0.0416963852743268),
 (2966, 0.041672126549754634),
 (131, 0.041623286124929715),
 (4591, 0.041614974877138194),
 (3342, 0.04155938241874874),
 (1549, 0.04152456587373835),
 (365, 0.041511373573657376),
 (600, 0.041497950655907494),
 (1902, 0.041494266734359346),
 (132, 0.0414353184294162),
 (2363, 0.04139242550548305),
 (2031, 0.04137805178778522),
 (4095, 0.041367464332712614),
 (4004, 0.041318126438368546),
 (2062, 0.04124784696642675),
 (4341, 0.04111390317136778),
 (2618, 0.04109526389211088),
 (1953, 0.04107400743981943),
 (1034, 0.04100781639261589),
 (368, 0.040978491128888836),
 (1119, 0.040943323407338986),
 (304, 0.04087469596204114),
 (790, 0.0408520890501874),
 (2384, 0.04085131270080937),
 (2452, 0.040758353204022206),
 (4205, 0.040660694645605344),
 (331, 0.0406264864680235),
 (2807, 0.04060157988002982),
 (3304, 0.04059407245304819),
 (786, 0.040584070124346464),
 (3817, 0.04056679802014421),
 (14, 0.04056071472295475),
 (1767, 0.040517620546920874),
 (1017, 0.040484317171845176),
 (3632, 0.040477949855593616),
 (1651, 0.04044064067999742),
 (1310, 0.040321395880404856),
 (2140, 0.040298705019056566),
 (1880, 0.04028522637544178),
 (1016, 0.04024491220814876),
 (3308, 0.04013767297844768),
 (536, 0.04010240011913248),
 (687, 0.040011164630407776),
 (4623, 0.03992367973666784),
 (4358, 0.03992352022777469),
 (160, 0.03991322779864718),
 (1654, 0.039906731171626006),
 (2685, 0.03987196633468217),
 (2494, 0.03984948710648817),
 (2641, 0.0398411942523841),
 (3072, 0.039839225505717155),
 (3174, 0.039811203416337086),
 (4492, 0.039749586295136106),
 (1845, 0.039669672764187355),
 (1534, 0.03958796093404667),
 (704, 0.03958439143170632),
 (63, 0.03950829879763227),
 (3162, 0.0394931931554595),
 (2548, 0.039477618206045555),
 (182, 0.039469475789603144),
 (274, 0.039375904902667846),
 (2134, 0.03929419893947592),
 (986, 0.039274026588482044),
 (4126, 0.03926264736259776),
 (138, 0.039092319467090214),
 (3505, 0.039084861023013),
 (189, 0.03901414611880327),
 (935, 0.03897868318776505),
 (4799, 0.038962918437266465),
 (2628, 0.03892968483868131),
 (901, 0.03890413572948859),
 (2646, 0.03882467199771726),
 (1325, 0.038807929902343316),
 (617, 0.038779729337377236),
 (2953, 0.038717298237737244),
 (1002, 0.03870653545211359),
 (4331, 0.03870411429079019),
 (3058, 0.038698366977535065),
 (571, 0.03863448477285931),
 (1940, 0.03862982259990104),
 (467, 0.03858001698770679),
 (963, 0.03844867509519363),
 (2228, 0.03844534362974592),
 (21, 0.038399200474328446),
 (897, 0.03829430879047922),
 (602, 0.03829217119761609),
 (3020, 0.03828763592972414),
 (2444, 0.03826467289909681),
 (126, 0.03823371349577097),
 (2372, 0.03822504225253927),
 (2255, 0.03821095944988613),
 (3738, 0.03818790009751652),
 (208, 0.03806434619502724),
 (3438, 0.03795822654266285),
 (2758, 0.037902982584777714),
 (672, 0.03778763094393727),
 (4558, 0.03775004870034415),
 (1118, 0.03773016121384159),
 (423, 0.03763111198463731),
 (413, 0.03751527772206031),
 (430, 0.03748554314032586),
 (781, 0.03746108415393455),
 (254, 0.037439296718497383),
 (770, 0.03740386637095286),
 (2196, 0.037340378361860826),
 (3070, 0.037325707427867325),
 (1519, 0.0372545535825306),
 (1359, 0.03725203904304634),
 (2876, 0.037210539717658225),
 (3, 0.03709160391763315),
 (4490, 0.03706542424238733),
 (746, 0.03704693859290195),
 (4348, 0.036995919699124566),
 (1806, 0.03690136561046954),
 (3558, 0.03684983874476315),
 (4510, 0.03682041174871472),
 (472, 0.036811626022375615),
 (2382, 0.03680732338214429),
 (1473, 0.036763506030197825),
 (3390, 0.03675190669632402),
 (3742, 0.03670013014817535),
 (410, 0.03669852346017225),
 (951, 0.03664597891091286),
 (814, 0.03664335244925964),
 (3899, 0.0366243011699712),
 (3387, 0.036597770930998426),
 (3908, 0.03655936425694485),
 (2708, 0.03650424257638627),
 (2682, 0.036499981005913985),
 (4777, 0.036464616953965266),
 (341, 0.03646145984635835),
 (2588, 0.03641320490039222),
 (653, 0.03629762517383499),
 (1938, 0.03626029172121381),
 (3320, 0.036222731260514854),
 (4594, 0.036211289638395885),
 (2017, 0.03617231832410343),
 (1229, 0.03616515000551727),
 (2900, 0.03616212975689182),
 (866, 0.03614344252318193),
 (1959, 0.036103807838033464),
 (59, 0.03606224144222978),
 (572, 0.03605869541438926),
 (2068, 0.03602745467245952),
 (2848, 0.036018320791745204),
 (302, 0.035983326599565144),
 (361, 0.03597835304919628),
 (1280, 0.0359633669271033),
 (3428, 0.03593917354672342),
 (2393, 0.03591684479750344),
 (657, 0.03584955656344991),
 (4675, 0.03583963303248084),
 (680, 0.0358159161823768),
 (2009, 0.035789295082823816),
 (107, 0.03577128630223237),
 (2013, 0.03572996487006868),
 (2635, 0.03570439301242668),
 (125, 0.03570382007319434),
 (1515, 0.03566628046717053),
 (1021, 0.03555857766291095),
 (4178, 0.03543356523714564),
 (4781, 0.03538500958250764),
 (445, 0.0352787464142827),
 (3295, 0.03526136981308003),
 (2566, 0.03525886858451377),
 (2902, 0.035237953362929154),
 (3737, 0.03523327436201798),
 (1423, 0.03522550552708424),
 (1247, 0.03521414071163471),
 (1492, 0.0351934275577208),
 (3735, 0.03515877379346761),
 (2352, 0.035146658683592916),
 (488, 0.03513035300937928),
 (1322, 0.0350494776040282),
 (4618, 0.03491839011154725),
 (2291, 0.03487876804781133),
 (229, 0.03480076354766454),
 (2589, 0.03477542282422868),
 (330, 0.03469229549248053),
 (325, 0.03460085140142171),
 (4657, 0.034515403530584174),
 (3067, 0.03437144140254008),
 (1169, 0.034244866269581106),
 (1771, 0.03421457673243647),
 (3849, 0.03418042878614211),
 (1829, 0.03412454404922096),
 (3449, 0.03411625848639638),
 (102, 0.034074651808063246),
 (490, 0.034051626905043736),
 (2199, 0.03401475250166159),
 (4403, 0.03397687537813302),
 (3535, 0.033962485981145624),
 (3150, 0.0338980426244377),
 (3674, 0.03386743530083462),
 (334, 0.033757867532411195),
 (4542, 0.03369512523253862),
 (153, 0.033668409601700075),
 (235, 0.033600596642509445),
 (1688, 0.033561942889567514),
 (2123, 0.033561884596017055),
 (154, 0.03352158777951829),
 (773, 0.033492372930917336),
 (1068, 0.03347861425746478),
 (148, 0.03347431940241488),
 (3366, 0.03347189438373197),
 (4483, 0.03333343729215656),
 (4203, 0.033297443596939265),
 (3808, 0.03318173486593662),
 (1238, 0.03317335381421488),
 (3500, 0.033171123769792255),
 (11, 0.03315473144179318),
 (1189, 0.033149991376860116),
 (4472, 0.033090473629874384),
 (122, 0.033048099563606805),
 (1677, 0.03298501216771888),
 (3223, 0.03297984460257137),
 (3793, 0.03292462757189249),
 (3298, 0.03292328879594822),
 (730, 0.03286444584184239),
 (3398, 0.03280193113332651),
 (3522, 0.03276591317268054),
 (2111, 0.0327635187342887),
 (1173, 0.03273471088538822),
 (2260, 0.03272199543390157),

In [ ]:
def recommend(movie):
    movie_index=int(movies[movies['title']==movie].index[0])
    l=sorted(list(enumerate([float(dist) for dist in list(similarity[movie_index])])),reverse=True,key=lambda x:x[1])
    movie_indices=[]
    for touple in l[0:5]:
        movie_indices.append(touple[0])
    movies_id=[]
    for index in movie_indices:
        movies_id.append(movies['movie_id'][index])
    
    id=[int(id) for id in movies_id]
    return id

In [ ]:
recommend('Batman')

[268, 2661, 415, 364, 49026]